server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/q297218757/spring-cloud-myself    # 配置git仓库的地址
          search-paths: spring-cloud-config                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 18707751075@163.com                                              # git仓库的账号
          password: czc08061                                             # git仓库的密码
